In [1]:
import numpy as np

# ***Creating Numpy Arrays from Python list***

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
np.array([1,2,3,4], dtype ='float32')

array([1., 2., 3., 4.], dtype=float32)

In [5]:
a = np.array([[1,2,3],
             [4,5,6]])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.shape

(2, 3)

In [8]:
a.ndim

2

In [9]:
a.dtype

dtype('int64')

In [10]:
a.size

6

### ***Creating Numpy Array from Scratch***
`zeros,one,full,arange,linespace` 

In [13]:
np.zeros([2,4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
np.ones([3,5], dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
np.full([3,5],6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### `random`

In [34]:
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [35]:
np.random.normal(0,1, (3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [36]:
np.random.randint(0,10,(4,5))

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3]])

In [37]:
np.random.rand(4,4)

array([[0.65314004, 0.17090959, 0.35815217, 0.75068614],
       [0.60783067, 0.32504723, 0.03842543, 0.63427406],
       [0.95894927, 0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 , 0.6235101 ]])

# ***Array Indexing & Slicing*** 

### ***One-demensional subarray***

In [54]:
x1 = np.random.randint(20, size = 6)

In [39]:
x1

array([15, 13, 16, 17,  5,  9])

In [44]:
x1[4] , x1[0] , x1[-1]

(np.int64(5), np.int64(15), np.int64(9))

### ***Multi-dimensional array***

In [46]:
x2 = np.random.randint(10,size = (3,4))

In [47]:
x2

array([[7, 5, 9, 0],
       [2, 7, 2, 9],
       [2, 3, 3, 2]])

In [50]:
x2[0,0] , x2[0][0]

(np.int64(7), np.int64(7))

In [51]:
x2[0,0] = 1000

In [52]:
x2

array([[1000,    5,    9,    0],
       [   2,    7,    2,    9],
       [   2,    3,    3,    2]])

### ***Slicing***

In [55]:
x1

array([14,  3, 17, 18, 14,  9])

In [56]:
x1[0:3]

array([14,  3, 17])

In [57]:
x1[::2]

array([14, 17, 14])

In [58]:
x2

array([[1000,    5,    9,    0],
       [   2,    7,    2,    9],
       [   2,    3,    3,    2]])

In [60]:
x2[:2,:3]

array([[1000,    5,    9],
       [   2,    7,    2]])

In [64]:
x2[:2,:2]

array([[1000,    5],
       [   2,    7]])

### ***Reshaping or Array & Transpose*** 

In [66]:
grid = np.arange(1,10)
grid.shape

(9,)

In [68]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
x = np.array([1,2,3])
x.shape

(3,)

In [72]:
x.reshape(3,1).shape

(3, 1)

In [73]:
x = np.array([[1.,2.],[3.,4.]])

In [74]:
x

array([[1., 2.],
       [3., 4.]])

In [75]:
x.T

array([[1., 3.],
       [2., 4.]])

### ***Array Concatenation and Splitting***

In [76]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [78]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [79]:
grid = np.array([[1, 2, 3], 
                 [4, 5, 6]])
grid 

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
np.concatenate((grid,grid),axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [82]:
np.concatenate((grid,grid),axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [83]:
# vstack
x = np.array([1,2,3])
grid =np.array([[9,8,7],[6,5,4]])

In [84]:
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [86]:
# horizontall stack 
y = np.array([[99],[99]])

np.hstack((y,grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

### ***Splitting of Array***

In [87]:
x = np.array([1,2,3,4,5,6,7,8,9,0])
x1,x2,x3 = np.split(x,[3,5])

In [88]:
x1

array([1, 2, 3])

In [89]:
x2

array([4, 5])

In [90]:
x3

array([6, 7, 8, 9, 0])

### ***Broadcasting and Vectorized operations***

In [92]:
a = np.arange(3)
a

array([0, 1, 2])

In [93]:
a + 5 #Broadcasting

array([5, 6, 7])

In [96]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [97]:
a.shape , b.shape

((3,), (3, 3))

In [98]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [99]:
a * b 

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [101]:
c = np.arange(3).reshape((3,1))
c

array([[0],
       [1],
       [2]])

In [102]:
c + b


array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

### ***Manipulating & Comparing Arrays***

#### ***Agggregation***

In [103]:
list_number = [1,2,3]
ll = np.array(list_number)

In [104]:
sum(ll)

np.int64(6)

In [106]:
# Creating a massive Numpy array 

massive_array = np.random.random(10000)
massive_array

array([0.96951851, 0.10160699, 0.24808099, ..., 0.0262725 , 0.5597873 ,
       0.21948844])

In [107]:
massive_array.shape

(10000,)

In [109]:
%timeit sum(massive_array)

415 μs ± 29.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [111]:
%timeit np.sum(massive_array)

2.98 μs ± 8.42 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [112]:
np.mean(massive_array)

np.float64(0.49731976571317293)

In [113]:
np.min(massive_array)

np.float64(4.011685566074341e-06)

#### ***Standard Deviation and Variance*** 

In [114]:
dog_height = [600,470,170,430,300]
dog_heigth = np.array(dog_height)

np.std(dog_heigth)

np.float64(147.32277488562318)

In [115]:
np.var(dog_heigth)

np.float64(21704.0)

In [116]:
np.sqrt(np.var(dog_heigth))

np.float64(147.32277488562318)

#### ***Sorting Array***

In [ ]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [118]:
np.argsort(x)

array([1, 0, 3, 2, 4])

In [120]:
np.random.seed(42)
MatA = np.random.randint(0,10,size = (4,6))
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [121]:
np.sort(MatA , axis = 0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [122]:
np.sort(MatA, axis = 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

### ***Linear Algebra***

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [125]:
B = np.array([[6, 5], [4, 3], [2, 1]])

In [ ]:
# dot Product 
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [127]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [129]:
B.T @ A  # chuyển vị B để 3x2 -> 2x3  

array([[36, 48, 60],
       [24, 33, 42]])

#### ***Dot Product Example***

In [130]:
np.random.seed(0)

sales_amounts = np.random.randint(20 , size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [131]:
import pandas as pd 

In [134]:
weekly_sales = pd.DataFrame(
    sales_amounts,
    index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
    columns=["Almond Butter", "Peanut Butter", "Cashew Butter"],
)
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [135]:
# Create a price array 
prices = np.array([10,8,12])

In [139]:
butter_prices = pd.DataFrame(
    prices.reshape(1, 3),
    index=["Price"],
    columns=["Almond Butter", "Peanut Butter", "Cashew Butter"],
)
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [140]:
weekly_sales.shape , prices.shape

((5, 3), (3,))

In [142]:
total_prices = weekly_sales @ prices
total_prices

Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142
dtype: int64